language: python
python:
  - 3.6
  - pypy3
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
install:
  - make dist
  - pip install dist/aioprometheus-*.whl
script:
  - make test
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install black; make style; fi
matrix:
  allow_failures:
    - python: pypy3
