language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - pypy3
os:
  - linux
git:
  depth: 1
before_install:
  - pip install pip --upgrade
  - pip install -r requirements.dev.txt
#  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install black; make check-style; fi
install:
  - pip install .
script:
  - make check-style
  - make test
  - make docs
  - make dist
matrix:
  allow_failures:
    - python: pypy3
