language: python
python:
  - 3.5
os:
  - linux
  - osx
install:
  - pip install --user -r requirements.dev.txt
  - pip install -e .
script:
    - make test
    - make docs
matrix:
  fast_finish: true
